### ISSUE TITLE
How to run these w/out docker?

### ISSUE THREAD

**Issue by jaidayal** [IntelAI/models#75]
Is there anyway to run these benchmarks without Docker? Many of us on HPC clusters don't use docker because we want as minimal and noise-free environment as possible. Being able to run w/out docker and containers helps that.

**Comment by dmsuehir** [comment]
@jaidayal We have instructions for running the launch_benchmark.py script without docker here: https://github.com/IntelAI/models/blob/master/docs/general/tensorflow/LaunchBenchmark.md#running-the-launch-script-on-bare-metal
In general, you'll need to make sure that your environment has all of the dependencies installed and leave out the `--docker-image` flag when you run the script.

We also have model packages, which are intended to be run without docker. It's a tar file that includes the scripts needed to run and the pretrained model (for inference packages). The model packages can be found at the [oneContainer portal](https://software.intel.com/content/www/us/en/develop/tools/containers/full-catalog.html). We also have direct links to our model zoo packages in the table [here](https://github.com/IntelAI/models/tree/master/benchmarks#tensorflow-use-cases) -- in the column labeled oneContainer Portal, there are links to the "Model Packages" in each row.

**Comment by jaidayal** [comment]
Okay, the Launch Benchmark script invokes a series of other scripts, which ultimately invoke the one that runs the actual application. If I am going to put something like numactl (or a separate launcher for a custom OS like mcexec) how would I do that? Ultimately, I want to run just the application and not a whole bunch of intermediary scripts.

**Comment by dmsuehir** [comment]
@jaidayal You could call the model script directly to bypass launch_benchmark.py. If you already have a launch_benchmark.py command that's working you can run that command with `--verbose` and that prints out a bunch of extra info including the actual model script command.

For example if I run:
```
python launch_benchmark.py \
    --in-graph /tmp/dmsuehir/resnet50_fp32_pretrained_model.pb \
    --model-name resnet50 \
    --framework tensorflow \
    --precision fp32 \
    --mode inference \
    --batch-size=1 \
    --socket-id 0 \
    --docker-image intel/intel-optimized-tensorflow:2.4.0 \
    --verbose
```
Toward the end of the log file, there's a line that says `Running:` followed by the model command:
```
Running: numactl --cpunodebind=0 --membind=0 python /workspace/intelai_models/inference/eval_image_classifier_inference.py --input-graph=/in_graph/resnet50_fp32_pretrained_model.pb --num-inter-threads=1 --num-intra-threads=28 --num-cores=28 --batch-size=1 --warmup-steps=10 --steps=50
```
That `eval_image_classifier_inference.py` script is in the model zoo repo [here](https://github.com/IntelAI/models/blob/master/models/image_recognition/tensorflow/resnet50/inference/eval_image_classifier_inference.py). Since I had `--socket-id 0` in my original launch_benchmark.py command, numactl is being used and you could modify those args to whatever you need. Note that part of the intermediate scripts within the model zoo is looking at your system (number of cores, etc) to set the optimal number of threads, etc for the model and there are env vars like `OMP_NUM_THREADS` that are also getting set. If you are bypassing the launch_benchmark.py script, you'll want to set those vars yourself. The [general best practices doc](https://github.com/IntelAI/models/blob/master/docs/general/tensorflow/GeneralBestPractices.md) has basic information on this but what each model does in the zoo might vary depending on what the model's engineer has found to be the best configs.

**Comment by dmsuehir** [comment]
Hi @jaidayal

Has your question from this issue been resolved? If so, can we close this issue?

Thanks,
Dina
