### ISSUE TITLE
Downloading the dataset

### ISSUE THREAD

**Issue by jaidayal** [IntelAI/models#76]
The link you've posted to download the dataset is broken. Furthermore, even after figuring out the right url, trying to download the 2012 dataset is nearly impossible; endless circular links leading nowhere. 

Is inceptionv3 maintained or is it a dead benchmark?

**Comment by dmsuehir** [comment]
In case this issue comes up again, the issue is with ImageNet's website. After logging in, it takes the user to the wrong location, and the user needs to correct the URL to go to the "2012" download page. This is already mentioned in our [imagenet instructions README](https://github.com/IntelAI/models/blob/master/datasets/imagenet/README.md) and that URL fix resolved the issue for Jai.
